# Generated by Django 4.1.5 on 2023-02-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='condition',
            new_name='record_company',
        ),
    ]
