# Generated by Django 4.1.5 on 2023-02-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_rename_condition_provider_record_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='record_company',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional'), ('Independiente', 'Independiente')], max_length=50, verbose_name='Discográfica'),
        ),
    ]
