# Generated by Django 4.1.5 on 2023-02-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_provider_address_alter_provider_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
