# Generated by Django 4.1.5 on 2023-01-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_image_products_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_image',
            field=models.ImageField(default='', upload_to='products_image', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
