# Generated by Django 4.1.5 on 2023-01-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='products_picture',
            field=models.ImageField(blank=True, null=True, upload_to='products_picture'),
        ),
    ]
