# Generated by Django 4.1.5 on 2023-01-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_products_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='products_picture',
        ),
        migrations.AddField(
            model_name='products',
            name='products_image',
            field=models.ImageField(blank=True, null=True, upload_to='products_image'),
        ),
    ]
