# Generated by Django 4.1.5 on 2023-02-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_products_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
